### ISSUE TITLE
Incorrect type hints in retriever (small issue)

### ISSUE THREAD

**Issue by KSneijders** [Divy1211/FileParser#1]
Type hints in the `Retriever` class for `min_ver` and `max_ver` have incorrect type hints.

They currently have: `tuple[int]`. Whilst it should be: `tuple[int, ...]`.
The first tells python to expect a tuple with 1 int, the second a tuple with any amount of ints.

For more information see:  
https://stackoverflow.com/a/47534998/7230293

**Comment by Divy1211** [comment]
This issue will be resolved in the upcoming `v0.0.3`!
